// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2AFtyqE3M0sDN-jXD8htD7C7lwoaqj1k',
    appId: '1:106532290243:web:ef7108e6fd685cbdc7ac76',
    messagingSenderId: '106532290243',
    projectId: 'calendar-2b2e8',
    authDomain: 'calendar-2b2e8.firebaseapp.com',
    storageBucket: 'calendar-2b2e8.appspot.com',
    measurementId: 'G-X0FJW36EGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvjLX13UuUgv2YjcFnPpKqtkOUtF-hd5g',
    appId: '1:106532290243:android:e7797f66d0b9f8b4c7ac76',
    messagingSenderId: '106532290243',
    projectId: 'calendar-2b2e8',
    storageBucket: 'calendar-2b2e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLjR0J24PvUAOTwM0hnD-KJYwI4hhQe00',
    appId: '1:106532290243:ios:e2e09d5b2ba202bec7ac76',
    messagingSenderId: '106532290243',
    projectId: 'calendar-2b2e8',
    storageBucket: 'calendar-2b2e8.appspot.com',
    iosClientId: '106532290243-qc1ihukn4ej7dj7r5tpoo1sj7emumuuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLjR0J24PvUAOTwM0hnD-KJYwI4hhQe00',
    appId: '1:106532290243:ios:e2e09d5b2ba202bec7ac76',
    messagingSenderId: '106532290243',
    projectId: 'calendar-2b2e8',
    storageBucket: 'calendar-2b2e8.appspot.com',
    iosClientId: '106532290243-qc1ihukn4ej7dj7r5tpoo1sj7emumuuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendar',
  );
}
